name = "www-napochaan-com"
account_id = "cda8b0a2b410e1ff3a5bcc72c7e46f72"
main = "./worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = true

[[rules]]
type = "Data"
globs = ["**/*.ttf", "**/*.otf"]
fallthrough = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[images]
binding = "IMAGES"

[vars]
BASE_URL = "http://localhost:3000"
NODE_ENV="development"
NEXTJS_ENV="development"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "napochaan-next-cache"

[[d1_databases]]
binding = "NEXT_TAG_CACHE_D1"
database_id = "76caa407-d227-42a4-8c69-6c6859edcfd0"
database_name = "napochaan-next-tag-cache"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "www-napochaan-com"

[[durable_objects.bindings]]
name = "NEXT_CACHE_DO_QUEUE"
class_name = "DOQueueHandler"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DOQueueHandler"]

[env.production.vars]
BASE_URL = "https://napochaan.com"
NODE_ENV="production"
NEXTJS_ENV="production"

[env.production.images]
binding = "IMAGES"

[[env.production.routes]]
pattern = "napochaan.com"
custom_domain = true

[env.production.observability.logs]
enabled = true

[[env.production.r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "napochaan-next-cache-prod"

[[env.production.d1_databases]]
binding = "NEXT_TAG_CACHE_D1"
database_id = "76caa407-d227-42a4-8c69-6c6859edcfd0"
database_name = "napochaan-next-tag-cache-prod"

[[env.production.services]]
binding = "WORKER_SELF_REFERENCE"
service = "www-napochaan-com-production"

[[env.production.durable_objects.bindings]]
name = "NEXT_CACHE_DO_QUEUE"
class_name = "DOQueueHandler"

[env.staging.vars]
BASE_URL = "https://staging.napochaan.com"
NODE_ENV="production"
NEXTJS_ENV="production"

[env.staging.images]
binding = "IMAGES"

[[env.staging.routes]]
pattern = "staging.napochaan.com"
custom_domain = true

[env.staging.observability.logs]
enabled = true

[[env.staging.r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "napochaan-next-cache-staging"

[[env.staging.d1_databases]]
binding = "NEXT_TAG_CACHE_D1"
database_id = "6d5721f0-6223-4cb8-bc68-f37ff2f02b40"
database_name = "napochaan-next-tag-cache-staging"

[[env.staging.services]]
binding = "WORKER_SELF_REFERENCE"
service = "www-napochaan-com-staging"

[[env.staging.durable_objects.bindings]]
name = "NEXT_CACHE_DO_QUEUE"
class_name = "DOQueueHandler"
