import { css } from '@styled/css';

export const root = css({
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 'inline',
  minH: 'targetComfortable',
  px: '4',
  fontFamily: 'mono',
  fontSize: 'sm',
  fontWeight: 'semibold',
  lineHeight: 'snug',
  borderWidth: 'default',
  borderStyle: 'solid',
  borderColor: 'fg.default',
  borderRadius: 'none',
  cursor: 'pointer',
  transitionProperty: '[transform,background-color,color]',
  transitionDuration: 'snap',
  transitionTimingFunction: 'stepSnap',
  _hover: { transform: 'translate(3px, 3px)' },
  _focusVisible: { layerStyle: 'focusRing' },
  _disabled: { opacity: 'disabled', cursor: 'not-allowed', _hover: { transform: 'none' } },
  '&[data-variant="solid"]': {
    bg: 'accent.solid',
    color: 'fg.onSolid',
    borderColor: 'accent.solid',
    _hover: { bg: 'accent.solidHover' },
  },
  '&[data-variant="outline"]': { bg: 'transparent', color: 'fg.default' },
  '&[data-variant="danger"]': {
    bg: 'danger.solid',
    color: 'fg.onDanger',
    borderColor: 'danger.solid',
    _hover: { bg: 'danger.solidHover' },
  },
});
