import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import payload from 'payload';

import { dayjs } from '@utils/dayjs';

import { r2Bucket } from '../payload.config';

import { saveMediaFile } from './save-media-file';
import { applyBodySentinels, collectBodyMedia } from './sentinelize-body-media';

import type { Blog, Gallery, Media, Work } from '@payload-types';
import type { SerializedEditorState } from '@payloadcms/richtext-lexical/lexical';
import type { Payload, SanitizedConfig } from 'payload';

// Decouples seed data from migrations: dumps the live CMS content to editable
// JSON under src/seed/data/. The companion `seed:import` script upserts it back.
// System columns (id / timestamps / SEO meta / upload sizes) are stripped so the
// files stay hand-editable; media relationships collapse to a filename string.

const dirname = path.dirname(fileURLToPath(import.meta.url));
const dataDir = path.resolve(dirname, 'data');
const assetsDir = path.resolve(dirname, 'assets');
const blogAssetsDir = path.resolve(assetsDir, 'blog');

// Keys Payload manages for us — never hand-edited, regenerated on import.
// `globalType` is injected by findGlobal and rejected by updateGlobal on the way back.
// `meta` is the seoPlugin's SEO group (regenerated on import) on news/works/blog/gallery —
// but the `logs` collection has its own required content field also named `meta` (the
// メタラベル type label), so that one slug must keep it (see `LOGS_SYSTEM_KEYS`).
// `_order` is the orderable fractional index (gallery) — regenerated by creation order on import.
// (`homeTop` is a `ui` field — purely presentational, carries no data, so it never appears in
// find() results and needs no stripping here.)
const SYSTEM_KEYS = ['id', 'createdAt', 'updatedAt', 'meta', 'sizes', 'globalType', '_order'] as const;
const LOGS_SYSTEM_KEYS = SYSTEM_KEYS.filter((key) => key !== 'meta');

const isPlainObject = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);

// Recursively drop the generated `id` Payload injects into array-field rows
// (profile.love[].id, skillGroups[].id, contacts[].id ...). richText bodies keep
// their lexical shape untouched — they live under keys we never recurse-strip.
const stripArrayRowIds = (value: unknown): unknown => {
  if (Array.isArray(value)) return value.map((item) => stripArrayRowIds(item));
  if (!isPlainObject(value)) return value;

  return Object.fromEntries(Object.entries(value).flatMap(([key, val]) => (key === 'id' ? [] : [[key, stripArrayRowIds(val)]])));
};

const stripKeys = (doc: object, keys: readonly string[]): Record<string, unknown> => Object.fromEntries(Object.entries(doc).filter(([key]) => !keys.includes(key)));

const stripSystemKeys = (doc: object): Record<string, unknown> => stripKeys(doc, SYSTEM_KEYS);

// dayOnly date fields (works.date, news/blog.publishedAt, logs.date) are stored as
// a UTC instant but carry no time-of-day meaning. Emit them as a bare RFC3339
// full-date in JST (Asia/Tokyo) so the JSON matches the admin picker (displayFormat
// yyyy-MM-dd) and stays unambiguous when hand-edited. A non-string value is left as-is.
const toDayDate = (value: unknown): unknown => (typeof value === 'string' ? dayjs(value).tz('Asia/Tokyo').format('YYYY-MM-DD') : value);

// Reformat one date key in place, preserving the surrounding key order.
const formatDayField = (record: Record<string, unknown>, key: string): Record<string, unknown> => Object.fromEntries(Object.entries(record).map(([k, v]) => (k === key ? [k, toDayDate(v)] : [k, v])));

// A populated upload relationship (depth: 1) is the Media object; pull its
// filename so the import side can re-resolve the file from src/seed/assets.
const mediaFilename = (value: number | Media | null | undefined): string | undefined => {
  if (value === null || value === undefined) return undefined;
  if (typeof value === 'number') return undefined;
  return value.filename ?? undefined;
};

// Lexical richText: the generated body shape carries an index signature the
// serialized lexical types don't, so coerce once at this read boundary (same
// rationale as import.ts's `asRichText`).
const asEditorState = (value: unknown): SerializedEditorState => value as unknown as SerializedEditorState;

// True only for a value shaped like a lexical editor state (an object whose
// `root.children` is an array). Works bodies are optional, so an absent body
// (undefined / null / non-editor-state) must pass through untouched.
const isEditorState = (value: unknown): boolean => isPlainObject(value) && isPlainObject(value.root) && Array.isArray(value.root.children);

// Sentinelize the lexical `body` in place, preserving the surrounding key order
// (mirrors formatDayField) so the exported JSON diff stays minimal. No-ops when
// the body is absent / not an editor state (works bodies are optional; blog
// always has one, so blog is unchanged).
const sentinelizeBodyField = (record: Record<string, unknown>): Record<string, unknown> =>
  Object.fromEntries(
    record.body === undefined || !isEditorState(record.body) ? Object.entries(record) : Object.entries(record).map(([k, v]) => (k === 'body' ? [k, applyBodySentinels(asEditorState(v))] : [k, v])),
  );

const toWorkRecord = (work: Work): Record<string, unknown> => {
  const { thumbnail, ...rest } = work;
  const thumbnailFile = mediaFilename(thumbnail);
  const base = sentinelizeBodyField(formatDayField(stripSystemKeys(rest), 'date'));
  if (thumbnailFile === undefined) return base;
  return { ...base, thumbnailFile };
};

const toGalleryRecord = (item: Gallery): Record<string, unknown> => {
  const { image, ...rest } = item;
  const imageFile = mediaFilename(image);
  const base = stripSystemKeys(rest);
  if (imageFile === undefined) return base;
  return { ...base, imageFile };
};

const writeJson = async (instance: Payload, slug: string, records: readonly unknown[]): Promise<void> => {
  const filePath = path.resolve(dataDir, `${slug}.json`);
  await writeFile(filePath, `${JSON.stringify(records, null, 2)}\n`, 'utf8');
  instance.logger.info(`[seed:export] wrote ${records.length} ${slug} → ${path.relative(process.cwd(), filePath)}`);
};

const exportWorks = async (instance: Payload): Promise<void> => {
  // Export in date order (oldest first) for a stable JSON diff. Admin and public
  // reads both order by `-date` at query time, so no per-record ordinal is stored.
  const { docs } = await instance.find({ collection: 'works', depth: 1, limit: 0, sort: 'date', overrideAccess: true });
  for (const doc of docs) {
    await saveMediaFile(doc.thumbnail, assetsDir, r2Bucket, instance.logger);
    // Works bodies are optional and may embed lexical upload nodes (mirrors
    // blog). Only walk a present body; keep the binaries alongside the thumbnail
    // in the root assetsDir (no works subfolder).
    if (!isEditorState(doc.body)) continue;
    for (const media of collectBodyMedia(asEditorState(doc.body))) {
      await saveMediaFile(media, assetsDir, r2Bucket, instance.logger);
    }
  }
  await writeJson(instance, 'works', docs.map(toWorkRecord));
};

const exportGallery = async (instance: Payload): Promise<void> => {
  const { docs } = await instance.find({ collection: 'gallery', depth: 1, limit: 0, sort: '_order', overrideAccess: true });
  for (const doc of docs) {
    await saveMediaFile(doc.image, assetsDir, r2Bucket, instance.logger);
  }
  await writeJson(instance, 'gallery', docs.map(toGalleryRecord));
};

// News / logs carry no media relationship — strip system keys only. (Blog
// bodies may embed lexical upload nodes, so blog has its own exporter below.)
// `logs.meta` is real content (the メタラベル type label), so logs keeps `meta`
// while news drops the seoPlugin-generated `meta` group.
const exportSimple = async (instance: Payload, slug: 'news' | 'logs', sort: string): Promise<void> => {
  const { docs } = await instance.find({ collection: slug, depth: 1, limit: 0, sort, overrideAccess: true });
  const keys = slug === 'logs' ? LOGS_SYSTEM_KEYS : SYSTEM_KEYS;
  const dateKey = slug === 'logs' ? 'date' : 'publishedAt';
  await writeJson(
    instance,
    slug,
    docs.map((doc) => formatDayField(stripKeys(doc, keys), dateKey)),
  );
};

const toBlogRecord = (doc: Blog): Record<string, unknown> => sentinelizeBodyField(formatDayField(stripSystemKeys(doc), 'publishedAt'));

// Blog bodies may embed lexical upload nodes; at depth: 1 each carries the full
// populated Media object, which is tied to this database's ids. Save every
// embedded binary under assets/blog/ and rewrite the value back to a portable
// `{ __file, __alt }` sentinel so `seed:import` (resolve-body-media) can
// re-resolve it against whatever database it runs on.
const exportBlog = async (instance: Payload): Promise<void> => {
  const { docs } = await instance.find({ collection: 'blog', depth: 1, limit: 0, sort: 'publishedAt', overrideAccess: true });
  for (const doc of docs) {
    for (const media of collectBodyMedia(asEditorState(doc.body))) {
      await saveMediaFile(media, blogAssetsDir, r2Bucket, instance.logger);
    }
  }
  await writeJson(instance, 'blog', docs.map(toBlogRecord));
};

const exportProfile = async (instance: Payload): Promise<void> => {
  const profile = await instance.findGlobal({ slug: 'profile', depth: 1, overrideAccess: true });
  const record = stripArrayRowIds(stripSystemKeys(profile));
  const filePath = path.resolve(dataDir, 'profile.json');
  await writeFile(filePath, `${JSON.stringify(record, null, 2)}\n`, 'utf8');
  instance.logger.info(`[seed:export] wrote profile → ${path.relative(process.cwd(), filePath)}`);
};

// Payload bin script entry point. Invoked by `pnpm seed:export`.
export const script = async (config: SanitizedConfig): Promise<void> => {
  await payload.init({ config });
  await mkdir(dataDir, { recursive: true });
  await mkdir(assetsDir, { recursive: true });
  await mkdir(blogAssetsDir, { recursive: true });
  await exportWorks(payload);
  await exportSimple(payload, 'news', 'publishedAt');
  await exportBlog(payload);
  await exportSimple(payload, 'logs', 'date');
  await exportGallery(payload);
  await exportProfile(payload);
  process.exit(0);
};
