name: setup node
description: setup node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ./.node-version

    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      with:
        version: 10.15.1

    - uses: actions/cache@v4
      id: pnpm-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-

    - name: Install Dependencies
      if: ${{ steps.pnpm-cache.outputs.cache-hit != 'true' }}
      run: pnpm install
      shell: bash