name: setup node
description: setup node

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - uses: actions/cache@v4
      id: bun-cache
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: ${{ runner.os }}-bun-

    - run: echo '${{ toJSON(steps.bun-cache.outputs) }}'
      shell: bash

    - name: Install Dependencies
      if: ${{ steps.bun-cache.outputs.cache-hit != 'true' }}
      run: bun install
      shell: bash
