import { describe, expect, it, vi } from 'vitest';

// `route.ts` is a Payload scaffold file regenerated by `payload generate:importmap` /
// re-scaffolding. Only the `HEAD` export is hand-added (Payload's endpoint dispatcher
// matches on exact method, so a HEAD request never reaches the 'get' media endpoint
// unless rewritten to GET first). This test guards that a future re-scaffold cannot
// silently drop it — the REST_* exports themselves are Payload's own generated
// plumbing and are not re-tested here.
vi.mock('@payloadcms/next/css', () => ({}));
vi.mock('@payload-config', () => ({ default: {} }));

const GET = vi.fn(async (request: Request) => new Response(request.method, { status: 200, headers: { 'x-test': '1' } }));

vi.mock('@payloadcms/next/routes', () => ({
  REST_GET: () => GET,
  REST_POST: () => vi.fn(),
  REST_DELETE: () => vi.fn(),
  REST_PATCH: () => vi.fn(),
  REST_PUT: () => vi.fn(),
  REST_OPTIONS: () => vi.fn(),
}));

const { HEAD } = await import('./route');

describe('HEAD /api/[...slug]', () => {
  it('is exported', () => {
    expect(HEAD).toBeDefined();
  });

  it('forwards to GET with the method rewritten to GET', async () => {
    GET.mockClear();
    const request = new Request('http://localhost/api/media/1', { method: 'HEAD' });
    await HEAD(request, {} as never);

    expect(GET).toHaveBeenCalledTimes(1);
    const [forwardedRequest] = GET.mock.calls[0] ?? [];
    expect(forwardedRequest).toBeInstanceOf(Request);
    expect(forwardedRequest?.method).toBe('GET');
  });

  it('cancels the GET response body instead of leaking the stream', async () => {
    const stream = new ReadableStream({
      start(controller) {
        controller.enqueue(new TextEncoder().encode('binary media bytes'));
        controller.close();
      },
    });
    const cancelSpy = vi.spyOn(stream, 'cancel');
    GET.mockImplementationOnce(async () => new Response(stream, { status: 200 }));

    const request = new Request('http://localhost/api/media/1', { method: 'HEAD' });
    await HEAD(request, {} as never);

    expect(cancelSpy).toHaveBeenCalledTimes(1);
  });

  it('returns a null-body response that passes through the GET status and headers', async () => {
    GET.mockImplementationOnce(async () => new Response('binary media bytes', { status: 200, headers: { 'content-type': 'video/mp4', 'content-length': '19' } }));

    const request = new Request('http://localhost/api/media/1', { method: 'HEAD' });
    const response = await HEAD(request, {} as never);

    expect(response.status).toBe(200);
    expect(response.headers.get('content-type')).toBe('video/mp4');
    expect(response.headers.get('content-length')).toBe('19');
    expect(response.body).toBeNull();
  });
});
