name: check code

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/**/*.tsx
      - src/**/*.ts

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-lint
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/modules/setup-node

      - run: bun run lint

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/modules/setup-node

      - run: bun run test

  type-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-type-check
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/modules/setup-node

      - run: bun run type-check

  next-on-pages:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-next-on-pages
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/modules/setup-node

      - run: bun next-on-pages
