name: check code

on:
  pull_request:
    paths:
      - src/**/*.tsx
      - src/**/*.ts

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/workflows/modules/install-dependencies

      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/workflows/modules/install-dependencies

      - run: npm run test
