name: check code

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - src/**/*.tsx
      - src/**/*.ts

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/modules/setup-node

      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/modules/setup-node

      - run: npm run test
