name: Deploy PR to Preview Storybook

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - ".storybook/**"
      - "**/components/**/*.tsx"
      - "**/components/**/*.stories.tsx"
      - "**/components/**/*.css.ts"
      - "public/**"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/modules/setup-node

      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Build Storybook
        run: npm run build-storybook
        env:
          STORYBOOK_BASE: "/${{ steps.repository.outputs.name }}/pr-preview/pr-${{ github.event.number }}"

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/
