name: Deploy PR to Preview Storybook

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - ".storybook/**"
      - "components/**"

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ./.node-version
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook
        env:
          STORYBOOK_BASE: "/${{ steps.repository.outputs.name }}/pr-preview/pr-${{ github.event.number }}"

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./storybook-static/
