name: Deploy Storybook

on:
  push:
    branches:
      - main
    paths:
      - ".storybook/**"
      - "components/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: repository
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook
        env:
          STORYBOOK_BASE: "/${{ steps.repository.outputs.name }}/main"

      - name: deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: storybook-static
          target-folder: main
