name: Lighthouse

on:
  push:
    branches-ignore:
      - main
      - gh-pages
      - renovate/**

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/modules/setup-node

      - name: run Lighthouse CI
        run: |
          bun install -g @lhci/cli
          bun run lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
