name: Lighthouse

on:
  push:
    branches-ignore:
      - main
      - gh-pages
      - renovate/**

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/workflows/modules/setup-node

      - name: Build for Lighthouse
        run: pnpm build

      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./.lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
