name: update status budge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  update-lighthouse-budge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    env:
      output-folder: lighthouse
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: create lightouse budge
        run: |
          npx lighthouse-badges \
            --url https://napochaan.com \
            --save-report \
            --output-path=${{ env.output-folder }}

      - name: deploy lighthouse status
        uses: JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29 # v4.6.8
        with:
          branch: gh-pages
          folder: ${{ env.output-folder }}
          target-folder: ${{ env.output-folder }}
