name: install dependencies
description: Install dependencies and create node_modules; if package.json has not been modified, create cached node_modules.

runs:
  using: composite
  steps:
    - uses: ./.github/workflows/modules/setup-node
    - uses: actions/cache@v3
      id: npm-cache
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      shell: bash

    - name: Install Dependencies
      if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm install
      shell: bash
